#!/usr/bin/env bash
#
# build.sh - Build the UIAutomator2 server APK using Unity's bundled Android
#            toolchain (JDK + SDK). No Android Studio required.
#
# Usage:
#   ./build.sh                 # build debug APK (default)
#   ./build.sh release         # build release APK
#   ./build.sh clean           # gradle clean
#   UNITY_VERSION=6000.0.55f1 ./build.sh   # force a specific editor
#
set -euo pipefail

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
UNITY_EDITORS_DIR="/Applications/Unity/Hub/Editor"
# Preferred editor; override with the UNITY_VERSION env var.
PREFERRED_UNITY="${UNITY_VERSION:-6000.3.9f1}"
# compileSdk the project targets - the editor's SDK must provide this platform.
REQUIRED_PLATFORM="android-34"

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"

log()  { printf '\033[1;34m[build]\033[0m %s\n' "$*"; }
err()  { printf '\033[1;31m[build:error]\033[0m %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

# ---------------------------------------------------------------------------
# Validate a candidate editor; echo "jdk|sdk|buildtools" on success.
# ---------------------------------------------------------------------------
inspect_editor() {
    local ver="$1"
    local base="$UNITY_EDITORS_DIR/$ver/PlaybackEngines/AndroidPlayer"
    local jdk="$base/OpenJDK"
    local sdk="$base/SDK"

    [ -x "$jdk/bin/java" ] || return 1
    [ -d "$sdk/platforms/$REQUIRED_PLATFORM" ] || return 1

    # Pick the highest available build-tools version.
    local bt_dir="$sdk/build-tools"
    [ -d "$bt_dir" ] || return 1
    local bt
    bt="$(ls "$bt_dir" 2>/dev/null | sort -V | tail -1)"
    [ -n "$bt" ] || return 1

    printf '%s|%s|%s' "$jdk" "$sdk" "$bt"
}

# ---------------------------------------------------------------------------
# Resolve which editor to use.
# ---------------------------------------------------------------------------
resolve_editor() {
    # 1. Try the preferred/forced version first.
    if [ -d "$UNITY_EDITORS_DIR/$PREFERRED_UNITY" ]; then
        if info="$(inspect_editor "$PREFERRED_UNITY")"; then
            CHOSEN_VERSION="$PREFERRED_UNITY"
            CHOSEN_INFO="$info"
            return 0
        fi
        err "Preferred editor $PREFERRED_UNITY lacks a valid Android toolchain; searching others..."
    else
        err "Preferred editor $PREFERRED_UNITY not found; searching others..."
    fi

    # 2. Fall back to the newest editor that has a valid toolchain.
    local ver
    for ver in $(ls "$UNITY_EDITORS_DIR" 2>/dev/null | sort -Vr); do
        if info="$(inspect_editor "$ver")"; then
            CHOSEN_VERSION="$ver"
            CHOSEN_INFO="$info"
            return 0
        fi
    done
    return 1
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
[ -d "$UNITY_EDITORS_DIR" ] || die "Unity editors dir not found: $UNITY_EDITORS_DIR"

resolve_editor || die "No Unity editor with a usable Android toolchain (JDK + SDK + $REQUIRED_PLATFORM) found under $UNITY_EDITORS_DIR"

IFS='|' read -r JDK_DIR SDK_DIR BUILD_TOOLS <<< "$CHOSEN_INFO"

log "Using Unity editor : $CHOSEN_VERSION"
log "JAVA_HOME          : $JDK_DIR"
log "ANDROID_SDK_ROOT   : $SDK_DIR"
log "build-tools        : $BUILD_TOOLS"
log "platform           : $REQUIRED_PLATFORM"

export JAVA_HOME="$JDK_DIR"
export ANDROID_SDK_ROOT="$SDK_DIR"
export ANDROID_HOME="$SDK_DIR"

# Point Gradle at the SDK (local.properties is gitignored & machine-specific).
printf '## Auto-generated by build.sh - do not edit.\nsdk.dir=%s\n' "$SDK_DIR" > local.properties
log "Wrote local.properties"

# Map the requested target to a gradle task.
TARGET="${1:-debug}"
case "$TARGET" in
    debug)   GRADLE_TASK="assembleDebug" ;;
    release) GRADLE_TASK="assembleRelease" ;;
    clean)   GRADLE_TASK="clean" ;;
    *)       GRADLE_TASK="$TARGET" ;;  # pass through any gradle task
esac

log "Running: ./gradlew $GRADLE_TASK -PbuildToolsOverride=$BUILD_TOOLS"
./gradlew "$GRADLE_TASK" -PbuildToolsOverride="$BUILD_TOOLS" --no-daemon

if [ "$GRADLE_TASK" = "assembleDebug" ]; then
    APK="app/build/outputs/apk/debug/app-debug.apk"
    [ -f "$APK" ] && log "APK ready: $PROJECT_DIR/$APK"
elif [ "$GRADLE_TASK" = "assembleRelease" ]; then
    APK="app/build/outputs/apk/release/app-release.apk"
    [ -f "$APK" ] && log "APK ready: $PROJECT_DIR/$APK"
fi

log "Done."
